import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Viewport } from 'next'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next js',
  description: 'Generated by create next app',
  
}

// export const viewport: Viewport = {
//     width:'width-device',
//     initialScale:0.1,
//     maximumScale:0.1,
//     userScalable:false,
// }





export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={inter.className}>{children}</body>
    </html>
  )
}
